/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "service_constants.h"

namespace ws {

const serviceConstants g_service_constants;

serviceConstants::serviceConstants() {
}

} // namespace

