// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "WebService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::ws;

class WebServiceHandler : virtual public WebServiceIf {
 public:
  WebServiceHandler() {
    // Your initialization goes here
  }

  int64_t findNode(const std::string& street, const std::string& postal) {
    // Your implementation goes here
    printf("findNode\n");
  }

  void calcShortestWay(std::vector<Coordinate> & _return, const std::string& algorithm, const int64_t startNode, const int64_t endNode) {
    // Your implementation goes here
    printf("calcShortestWay\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<WebServiceHandler> handler(new WebServiceHandler());
  shared_ptr<TProcessor> processor(new WebServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

